---

- name: Start windows update service
  win_service:
    name: wuauserv
    start_mode: manual
    state: started
  become: yes
  become_user: Administrator
  become_method: runas
  ignore_errors: yes
  failed_when: false
  tags:
    - updateOSWindows
  when: ansible_os_family == "Windows"

- name: Install all security, critical, and rollup updates without a scheduled task
  ansible.windows.win_updates:
    category_names:
      - SecurityUpdates
      - CriticalUpdates
      - UpdateRollups
    reboot: yes
  become: yes
  become_user: Administrator
  become_method: runas
  ignore_errors: yes
  failed_when: false
  #  async: 10000
  #poll: 0
  tags:
    - updateOSWindows
  when: ansible_os_family == "Windows"

  #- name: Reboot the machine with all defaults
  #  ansible.windows.win_reboot:
  #  poll: 0
  #  tags:
  #    - updateOSWindows
  #  when: ansible_os_family == "Windows"

- name: Disabled windows update service
  win_service:
    name: wuauserv
    start_mode: disabled
    state: stopped
  become: yes
  become_user: Administrator
  become_method: runas
  ignore_errors: yes
  failed_when: false
  tags:
    - updateOSWindows
  when: ansible_os_family == "Windows"

...
